/**
 * v2.3.0 — 把 public/sw.js 内容嵌入为 TS 字符串常量
 *
 * Vercel serverless function 部署时不复制 public/ 目录,
 * 而 esbuild 编译 .ts 也不支持 Vite 的 `?raw` 语法.
 *
 * 方案: vite build 之后, 读 public/sw.js 内容写到 api/sw-content.ts,
 *       api/sw.js.ts 直接 import 这个常量.
 *
 * v2.3.3 (2026-06-20): Vercel build 时 .vercelignore 把 public/ 排了,
 * 找不到源文件直接跳过——api/sw-content.ts + api/manifest-content.ts
 * 已经在仓库里 (上次本地 build 嵌入的产物), Vercel 直接用现成的就行.
 * 本地 dev/build 时 public/ 在, 仍会重新生成保持最新.
 */
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';

const ROOT = process.cwd();
const SW_SRC = join(ROOT, 'public', 'sw.js');
const MANIFEST_SRC = join(ROOT, 'public', 'manifest.json');
const SW_OUT = join(ROOT, 'api', 'sw-content.ts');
const MANIFEST_OUT = join(ROOT, 'api', 'manifest-content.ts');

// v2.3.3: public/ 不在 (Vercel build 环境) → 跳过, 用仓库里现成的 api/*-content.ts
if (!existsSync(SW_SRC) || !existsSync(MANIFEST_SRC)) {
  console.log(`⏭  embed-sw: public/ 不可见, 跳过 (用仓库里已嵌入的 api/sw-content.ts + api/manifest-content.ts)`);
  process.exit(0);
}

function escape(s) {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$');
}

const swContent = readFileSync(SW_SRC, 'utf-8');
writeFileSync(
  SW_OUT,
  `// Auto-generated by scripts/embed-sw.js. Do not edit.\n` +
  `export const SW_CONTENT: string = \`${escape(swContent)}\`;\n`,
  'utf-8'
);

const manifestRaw = readFileSync(MANIFEST_SRC, 'utf-8');
writeFileSync(
  MANIFEST_OUT,
  `// Auto-generated by scripts/embed-sw.js. Do not edit.\n` +
  `export const MANIFEST_CONTENT: string = ${JSON.stringify(manifestRaw)};\n`,
  'utf-8'
);

console.log(`✅ embedded: sw.js (${swContent.length} bytes), manifest.json (${manifestRaw.length} bytes)`);
