/**
 * v2.5.23.2 — 把 5 个 logo PNG 嵌入为 TS Buffer 数组
 *
 * 背景：.vercelignore 排除 public/，Vite build 时拿不到这 5 个 PNG，
 * 部署到 Vercel 后 favicon/apple-touch-icon/og-image 等全部 404。
 *
 * 方案 (复用 v2.3.3 sw-content.ts 模式)：
 *   1. 读 5 个 PNG → base64
 *   2. 写 api/icon-content.ts (export Buffer[])
 *   3. api/icon/[...path].ts 是 catch-all serverless function
 *   4. vercel.json rewrites 5 个路径 → /api/icon/<path>
 *
 * Vercel build 时如果 public/ 不可见 (Vercel .vercelignore 排除),
 * 跳过生成, 用仓库里已存在的 api/icon-content.ts (本地 dev/build 嵌入产物).
 */
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';

const ROOT = process.cwd();
const PUBLIC = join(ROOT, 'public');
const OUT = join(ROOT, 'api', 'icon-content.ts');

const ICONS = [
  { path: 'favicon.png', mime: 'image/png' },
  { path: 'apple-touch-icon.png', mime: 'image/png' },
  { path: 'images/favicon.png', mime: 'image/png' },
  { path: 'images/logo-512.png', mime: 'image/png' },
  { path: 'images/og-image.png', mime: 'image/png' },
];

if (!existsSync(PUBLIC)) {
  console.log(
    '⏭  embed-icons: public/ 不可见, 跳过 (用仓库里已嵌入的 api/icon-content.ts)',
  );
  process.exit(0);
}

const entries = [];
for (const icon of ICONS) {
  const src = join(PUBLIC, icon.path);
  if (!existsSync(src)) {
    console.log(`  ⚠ ${icon.path} not found, skipping`);
    continue;
  }
  const buf = readFileSync(src);
  entries.push({
    path: icon.path,
    mime: icon.mime,
    size: buf.length,
    b64: buf.toString('base64'),
  });
  console.log(`  ✓ ${icon.path} (${buf.length} B)`);
}

const code = `// Auto-generated by scripts/embed-icons.js. Do not edit.
export interface IconEntry {
  path: string;
  mime: string;
  size: number;
  buffer: Buffer;
}

export const ICON_CONTENT: IconEntry[] = [
${entries
  .map(
    (e) =>
      `  { path: ${JSON.stringify(e.path)}, mime: ${JSON.stringify(e.mime)}, size: ${e.size}, buffer: Buffer.from(${JSON.stringify(e.b64)}, 'base64') },`,
  )
  .join('\n')}
];

export function findIcon(reqPath: string): IconEntry | undefined {
  const normalized = reqPath.replace(/^\\//, '');
  return ICON_CONTENT.find((i) => i.path === normalized);
}
`;

writeFileSync(OUT, code);
console.log(
  `\n✓ embed-icons: ${entries.length} icons written to ${OUT} (${(code.length / 1024).toFixed(1)} KB)`,
);
