/**
 * v2.3.0 — 把 public/sw.js 内容嵌入为 TS 字符串常量
 *
 * Vercel serverless function 部署时不复制 public/ 目录,
 * 而 esbuild 编译 .ts 也不支持 Vite 的 `?raw` 语法.
 *
 * 方案: vite build 之后, 读 public/sw.js 内容写到 api/_sw_content.ts,
 *       api/sw.js.ts 直接 import 这个常量.
 */
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const ROOT = process.cwd();
const SW_SRC = join(ROOT, 'public', 'sw.js');
const MANIFEST_SRC = join(ROOT, 'public', 'manifest.json');
const SW_OUT = join(ROOT, 'api', '_sw_content.ts');
const MANIFEST_OUT = join(ROOT, 'api', '_manifest_content.ts');

function escape(s) {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$');
}

const swContent = readFileSync(SW_SRC, 'utf-8');
writeFileSync(
  SW_OUT,
  `// Auto-generated by scripts/embed-sw.js. Do not edit.\n` +
  `export const SW_CONTENT: string = \`${escape(swContent)}\`;\n`,
  'utf-8'
);

const manifestRaw = readFileSync(MANIFEST_SRC, 'utf-8');
writeFileSync(
  MANIFEST_OUT,
  `// Auto-generated by scripts/embed-sw.js. Do not edit.\n` +
  `export const MANIFEST_CONTENT: string = ${JSON.stringify(manifestRaw)};\n`,
  'utf-8'
);

console.log(`✅ embedded: sw.js (${swContent.length} bytes), manifest.json (${manifestRaw.length} bytes)`);
