// Auto-generated by scripts/embed-sw.js. Do not edit.
export const SW_CONTENT: string = `/**
 * v2.3.0 — Service Worker
 *
 * 策略：
 *   1. 静态资源 (HTML/JS/CSS/SVG/images) — stale-while-revalidate
 *      优先返回 cache，后台异步更新 cache，下次访问拿到新版本
 *   2. JSON 数据 (activities.json / health_stats.json / training_advice.json)
 *      — cache-first + 24h TTL
 *      离线时直接用本地缓存，运动数据 24h 内基本不变
 *   3. /api/* — network-only（LLM 调用不能 cache 死）
 *   4. 其他 — network-first，失败 fallback 到 cache
 *
 * 版本：sports-fair-v2.3.0
 * 升级时改 CACHE_VERSION 即可触发旧 cache 清理
 */
const CACHE_VERSION = 'sports-fair-v2.3.0';
const STATIC_CACHE = \`\${CACHE_VERSION}-static\`;
const DATA_CACHE = \`\${CACHE_VERSION}-data\`;

const PRECACHE_URLS = [
  '/',
  '/manifest.json',
  '/images/favicon.png',
];

const DATA_URL_PATTERNS = [
  /\\/activities\\.json/,
  /\\/health_stats\\.json/,
  /\\/training_advice\\.json/,
  /\\/training_load\\.json/,
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(STATIC_CACHE).then((cache) => cache.addAll(PRECACHE_URLS))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) =>
      Promise.all(
        cacheNames
          .filter((name) => name !== STATIC_CACHE && name !== DATA_CACHE)
          .map((name) => caches.delete(name))
      )
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  const url = new URL(request.url);

  // 只处理 GET
  if (request.method !== 'GET') return;

  // API 请求：network-only (LLM 调用)
  if (url.pathname.startsWith('/api/')) {
    return; // 默认浏览器行为
  }

  // JSON 数据：cache-first + 后台更新
  if (DATA_URL_PATTERNS.some((p) => p.test(url.pathname))) {
    event.respondWith(staleWhileRevalidate(request, DATA_CACHE));
    return;
  }

  // 同源静态资源：stale-while-revalidate
  if (url.origin === self.location.origin) {
    event.respondWith(staleWhileRevalidate(request, STATIC_CACHE));
    return;
  }
});

async function staleWhileRevalidate(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cachedResponse = await cache.match(request);

  const fetchPromise = fetch(request)
    .then((networkResponse) => {
      if (networkResponse && networkResponse.status === 200) {
        cache.put(request, networkResponse.clone());
      }
      return networkResponse;
    })
    .catch(() => {
      // 网络挂了，离线时返回 cached
      if (cachedResponse) return cachedResponse;
      return new Response('Offline', { status: 503 });
    });

  return cachedResponse || fetchPromise;
}
`;
